import type {
  Conversation,
  Message,
  MutualGroup,
  NotificationItem,
  SharedMediaItem,
  User,
} from "./types"

export const CURRENT_USER: User = {
  id: "me",
  name: "Alex Rivera",
  color: "#4f8ef7",
  status: "online",
  role: "Founder & Engineer",
}

export const USERS: Record<string, User> = {
  me: CURRENT_USER,
  sarah: {
    id: "sarah",
    name: "Sarah Chen",
    color: "#ec4899",
    status: "online",
    role: "Product Designer",
    bio: "Designing calm interfaces. Coffee enthusiast.",
  },
  marcus: {
    id: "marcus",
    name: "Marcus Johnson",
    color: "#f59e0b",
    status: "away",
    role: "Frontend Engineer",
    bio: "I make pixels move. React all day.",
  },
  priya: {
    id: "priya",
    name: "Priya Patel",
    color: "#10b981",
    status: "online",
    role: "Engineering Lead",
    bio: "Shipping > perfect. Ask me about systems.",
  },
  david: {
    id: "david",
    name: "David Kim",
    color: "#8b5cf6",
    status: "offline",
    role: "Data Scientist",
    bio: "Numbers tell stories.",
  },
  lena: {
    id: "lena",
    name: "Lena Müller",
    color: "#06b6d4",
    status: "online",
    role: "Marketing",
    bio: "Words that convert.",
  },
}

export const CONVERSATIONS: Conversation[] = [
  {
    id: "c-sarah",
    participantId: "sarah",
    isGroup: false,
    name: "Sarah Chen",
    color: "#ec4899",
    status: "online",
    unread: 2,
  },
  {
    id: "c-design",
    participantId: "design",
    isGroup: true,
    name: "Design Team",
    color: "#4f8ef7",
    status: "online",
    unread: 5,
    members: ["sarah", "marcus", "lena", "me"],
  },
  {
    id: "c-marcus",
    participantId: "marcus",
    isGroup: false,
    name: "Marcus Johnson",
    color: "#f59e0b",
    status: "away",
    unread: 0,
  },
  {
    id: "c-priya",
    participantId: "priya",
    isGroup: false,
    name: "Priya Patel",
    color: "#10b981",
    status: "online",
    unread: 0,
  },
  {
    id: "c-eng",
    participantId: "eng",
    isGroup: true,
    name: "Engineering",
    color: "#10b981",
    status: "online",
    unread: 0,
    members: ["priya", "marcus", "david", "me"],
  },
  {
    id: "c-david",
    participantId: "david",
    isGroup: false,
    name: "David Kim",
    color: "#8b5cf6",
    status: "offline",
    unread: 0,
  },
  {
    id: "c-lena",
    participantId: "lena",
    isGroup: false,
    name: "Lena Müller",
    color: "#06b6d4",
    status: "online",
    unread: 0,
  },
]

// Fixed reference instant so SSR and client hydration agree (no Date.now()).
export const REFERENCE_NOW = Date.parse("2026-06-22T18:00:00.000Z")
const now = REFERENCE_NOW
const min = 60 * 1000
const t = (minsAgo: number) => new Date(now - minsAgo * min).toISOString()

export const MESSAGES: Record<string, Message[]> = {
  "c-sarah": [
    {
      id: "m1",
      conversationId: "c-sarah",
      senderId: "sarah",
      text: "Hey! Did you get a chance to look at the new dashboard mockups?",
      timestamp: t(240),
      status: "read",
      reactions: [],
    },
    {
      id: "m2",
      conversationId: "c-sarah",
      senderId: "me",
      text: "Just opened them — the dark theme looks incredible 🔥",
      timestamp: t(238),
      status: "read",
      reactions: [{ emoji: "❤️", by: ["sarah"] }],
    },
    {
      id: "m3",
      conversationId: "c-sarah",
      senderId: "sarah",
      text: "Here's the latest export so you can see it full res",
      timestamp: t(236),
      status: "read",
      reactions: [],
    },
    {
      id: "m4",
      conversationId: "c-sarah",
      senderId: "sarah",
      text: "",
      timestamp: t(235),
      status: "read",
      reactions: [{ emoji: "🤯", by: ["me", "marcus"] }],
      attachment: {
        type: "image",
        name: "dashboard-mockup.png",
        url: "/media/dashboard-mockup.png",
      },
    },
    {
      id: "m5",
      conversationId: "c-sarah",
      senderId: "me",
      text: "This is exactly the direction I wanted. The spacing feels so intentional.",
      timestamp: t(120),
      status: "read",
      reactions: [],
      replyTo: {
        messageId: "m4",
        senderName: "Sarah Chen",
        text: "dashboard-mockup.png",
      },
    },
    {
      id: "m6",
      conversationId: "c-sarah",
      senderId: "sarah",
      text: "I also attached the spec doc — let me know if the type scale works for dev.",
      timestamp: t(20),
      status: "read",
      reactions: [],
    },
    {
      id: "m7",
      conversationId: "c-sarah",
      senderId: "sarah",
      text: "",
      timestamp: t(19),
      status: "read",
      reactions: [],
      attachment: {
        type: "file",
        name: "design-spec-v3.pdf",
        size: "2.4 MB",
      },
    },
    {
      id: "m8",
      conversationId: "c-sarah",
      senderId: "me",
      text: "Perfect, reviewing now and I'll push the tokens today.",
      timestamp: t(4),
      status: "delivered",
      reactions: [],
    },
  ],
  "c-design": [
    {
      id: "d1",
      conversationId: "c-design",
      senderId: "marcus",
      text: "Pushed the new component library to staging 🚀",
      timestamp: t(180),
      status: "read",
      reactions: [{ emoji: "🚀", by: ["sarah", "lena", "me"] }],
    },
    {
      id: "d2",
      conversationId: "c-design",
      senderId: "lena",
      text: "Love it. Can we get a walkthrough before the launch?",
      timestamp: t(160),
      status: "read",
      reactions: [],
    },
    {
      id: "d3",
      conversationId: "c-design",
      senderId: "sarah",
      text: "Sharing the moodboard for the marketing site too",
      timestamp: t(60),
      status: "read",
      reactions: [],
      attachment: {
        type: "image",
        name: "moodboard.png",
        url: "/media/moodboard.png",
      },
    },
    {
      id: "d4",
      conversationId: "c-design",
      senderId: "me",
      text: "These are great. Let's sync at 3pm to align on the rollout.",
      timestamp: t(12),
      status: "delivered",
      reactions: [{ emoji: "👍", by: ["marcus"] }],
    },
  ],
  "c-marcus": [
    {
      id: "ma1",
      conversationId: "c-marcus",
      senderId: "marcus",
      text: "The animation timing feels a touch slow on mobile, thoughts?",
      timestamp: t(300),
      status: "read",
      reactions: [],
    },
    {
      id: "ma2",
      conversationId: "c-marcus",
      senderId: "me",
      text: "Agreed — let's drop it to 150ms ease.",
      timestamp: t(295),
      status: "read",
      reactions: [{ emoji: "✅", by: ["marcus"] }],
    },
    {
      id: "ma3",
      conversationId: "c-marcus",
      senderId: "marcus",
      text: "Done. Feels much snappier now.",
      timestamp: t(90),
      status: "read",
      reactions: [],
    },
  ],
  "c-priya": [
    {
      id: "p1",
      conversationId: "c-priya",
      senderId: "priya",
      text: "Can you review the API contract PR when you get a sec?",
      timestamp: t(420),
      status: "read",
      reactions: [],
    },
    {
      id: "p2",
      conversationId: "c-priya",
      senderId: "me",
      text: "On it. Looks clean overall, left two small comments.",
      timestamp: t(410),
      status: "read",
      reactions: [{ emoji: "🙏", by: ["priya"] }],
    },
  ],
  "c-eng": [
    {
      id: "e1",
      conversationId: "c-eng",
      senderId: "david",
      text: "Deploy went out, error rate is flat. 🎉",
      timestamp: t(500),
      status: "read",
      reactions: [{ emoji: "🎉", by: ["priya", "marcus", "me"] }],
    },
    {
      id: "e2",
      conversationId: "c-eng",
      senderId: "priya",
      text: "Nice work everyone. Standup notes in the doc.",
      timestamp: t(480),
      status: "read",
      reactions: [],
    },
  ],
  "c-david": [
    {
      id: "dv1",
      conversationId: "c-david",
      senderId: "david",
      text: "The cohort numbers are looking up this week.",
      timestamp: t(1440),
      status: "read",
      reactions: [],
    },
    {
      id: "dv2",
      conversationId: "c-david",
      senderId: "me",
      text: "Love to see it. Let's put it in the deck.",
      timestamp: t(1438),
      status: "read",
      reactions: [],
    },
  ],
  "c-lena": [
    {
      id: "l1",
      conversationId: "c-lena",
      senderId: "lena",
      text: "Draft of the launch copy is ready for review!",
      timestamp: t(720),
      status: "read",
      reactions: [],
    },
    {
      id: "l2",
      conversationId: "c-lena",
      senderId: "me",
      text: "Reading now — the headline is 🔥",
      timestamp: t(715),
      status: "read",
      reactions: [{ emoji: "😍", by: ["lena"] }],
    },
  ],
}

export const SHARED_MEDIA: Record<string, SharedMediaItem[]> = {
  default: [
    { id: "sm1", url: "/media/dashboard-mockup.png", alt: "Dashboard mockup" },
    { id: "sm2", url: "/media/workspace.png", alt: "Workspace photo" },
    { id: "sm3", url: "/media/mobile-app.png", alt: "Mobile app design" },
    { id: "sm4", url: "/media/moodboard.png", alt: "Design moodboard" },
    { id: "sm5", url: "/media/city.png", alt: "City skyline" },
    { id: "sm6", url: "/media/landscape.png", alt: "Mountain landscape" },
  ],
}

export const MUTUAL_GROUPS: MutualGroup[] = [
  { id: "g1", name: "Design Team", color: "#4f8ef7", members: 4 },
  { id: "g2", name: "Engineering", color: "#10b981", members: 4 },
  { id: "g3", name: "Launch War Room", color: "#f59e0b", members: 8 },
]

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n1",
    type: "message",
    text: "Sarah Chen sent you a message",
    conversationId: "c-sarah",
    timestamp: t(4),
    read: false,
  },
  {
    id: "n2",
    type: "reaction",
    text: "Marcus reacted 👍 to your message",
    conversationId: "c-design",
    timestamp: t(12),
    read: false,
  },
  {
    id: "n3",
    type: "mention",
    text: "Priya mentioned you in Engineering",
    conversationId: "c-eng",
    timestamp: t(40),
    read: true,
  },
]

export const QUICK_REACTIONS = ["👍", "❤️", "😂", "🎉", "🤯", "🙏"]

export const INCOMING_SNIPPETS = [
  "By the way, did you see the latest figures?",
  "Let me know when you're free to chat.",
  "Just pushed a fix for that bug 🐛",
  "This is looking really good!",
  "Can you take a look at this when you get a chance?",
  "Thanks for the quick turnaround 🙏",
  "I'll send over the notes shortly.",
  "Great call earlier — super productive.",
]
